### ISSUE TITLE
[Chris Week 7] RGB Lab

### ISSUE THREAD

**Issue by Chris-Ru** [Chris-Ru/P2-Chickens#31]
### Frontend
- [x] work with @dylanroman on [dropdown to change to grayscale](https://github.com/Chris-Ru/P2-Chickens/blob/main/src/main/resources/templates/Minilab/minilab4.1.html#L20-L35) on [grayscale page](https://github.com/Chris-Ru/P2-Chickens/blob/main/src/main/resources/templates/Minilab/minilab4.1.html)

### Backend
- [x] copy backend from [mort code](https://github.com/Chris-Ru/P2-Chickens/blob/main/src/main/java/com/example/sping_portfolio/Minilab/GrayScale.java) for rob lab
- [x] figure out [grayscale through backend](https://github.com/Chris-Ru/P2-Chickens/blob/main/src/main/java/com/example/sping_portfolio/controllers/minilabs.java#L51) with @dylanroman

**Comment by D1935827V** [comment]
Great College Board stuff and notes: https://docs.google.com/document/d/1lu7N6icRQ2mdnQk3K3PgXMYV9513hccZgVbMbaTcxqM/edit
I liked the greyscaling: and there are lots of artifacts on the ticket.
Individual 3/3 because has lots of contributions in commit history and good individual contributions in video.
