### ISSUE TITLE
Review Week 9

### ISSUE THREAD

**Issue by Chris-Ru** [Chris-Ru/P2-Chickens#40]
Name|Video|Total Score
------|------|------
Chris|[Video](https://youtu.be/RyTYjL2eSCg)|7.5/8
Dylan|[Video](https://drive.google.com/file/d/12ymd0-VrCE38dU2Y5IFjJH3J8NxgKrGa/view?usp=sharing)| 7.5/8
Shekar|[Video](https://drive.google.com/file/d/1T8z_8yiqLVDe7Ttm1ijIoH3oRufjw0Ug/view?usp=sharing)| 7.6/8
Sam|[Video](https://drive.google.com/file/d/1DPW3zwiZghjNHqvehzoh4_D19Rai6xHg/view?usp=sharing)| 7.3/8

**Comment by jm1021** [comment]
Grading: Chris Rubin
Grader: John Mortensen

It is unfortunate that group is not providing more feedback.  Here are some of my thoughts.
1.) Palindrome.   You shared several methods.  Built in to custom methods.  These clearly line up to college board.  However, you did not really use anything from CB memories or experience to show parallels.  It looked like you handled case in some of your algorithms.   To make these better you would handle space and punctuation, these are usually thrown out and make a better algorithm.  Try to handle something like "A man, a plan, a canal, Panama."
2.) Deployment.  It was nice to see multiple terminal windows open running Nginx and your service.  In this type of discussion, you could make it more thorough by showing Nginx and service configuration files.  Also, you could talk about updating and restarting.  

I could pick at a lot of things with rubric.  Trying to make this interesting is a skill that I don't think you ventured into much.  Palindrom algos could be more robust, Deployment could be more complete.  5.25/6

I like that you highlight Dylan's notebook, that is an example of trying to add something extra to presentation.  1.75/2

**Comment by jm1021** [comment]
Grading: Sam
Grader: John Mortensen
no video

**Comment by shekark642** [comment]
Grading: Chris
Grader: Shekar

I like your in depth observations and notations of java, it is good that you highlighted code with your cursor to point out to the audience that you know what you are talking about
![image](https://user-images.githubusercontent.com/72948731/139910915-25385dcc-79a2-4f9c-b272-ed21f893bf03.png
The high level technical talk also helps

Great usage of screen when talking about deployment, the three monitors shows all the different windows and expertise needed to deploy, and by using this, it makes it easier since you don't have to go back to the different windows to show everything. Easy on the eyes for a viewer as well.
![image](https://user-images.githubusercontent.com/72948731/139911306-472188ce-98f0-44f3-8a38-8e93b53a8cc3.png)

One thing to improve is the voice! It sounds like you are really tired (which you may be). But if you put on a pretend voice to be more excited about it, it will make the project come alive, and an audience will also be excited with you when you show all of your hard achievements

**Comment by samkoenig9** [comment]
Grading: Dylan
Grader: Sam

Comments:
I thought that you went over your topic really well and everything you talked about was clear, precise, and easy to understand.
I also liked how you showed the paper sketch of your GCF code. This shows your brainstorming to visualize and understand what the code has to do.

![image](https://user-images.githubusercontent.com/72891935/139913840-74389989-f41a-416e-9191-e08002b6f874.png)

There aren't any major issues I can see except that the beginning of the video seems cut off. Overall, great job!

**Comment by shekark642** [comment]
Grading Sm

**Comment by shekark642** [comment]
Grading: Sam
Grader: Shekar

I like that you show mastery of java by usage of grayscale. By showing it in command prompt, I knew that you were professional and understood what you were talking about. Good usage of technical terms.

Great job showing the front end as well. This showed that the code actually worked and could be implemented
![image](https://user-images.githubusercontent.com/72948731/140198738-6ee7d984-8666-4452-9105-e178a9b46fff.png)

One thing to do better is to maybe be a bit louder. I don't know if that is possible, but if you could be closer to the mic or something, it would be easier to hear you talk about the things you did on the project.

**Comment by shekark642** [comment]
Grading: Dylan
Grader: Shekar

Good job on presentation. Good voice and video was good quality so I could actually see what you were doing.
What was also very good was that you showed straight in the beginning what units you did on CB. This was helpful since we knew what you were doing for the project and what concepts your technicals were about. You got straight to the point and clarified what this technical was
![image](https://user-images.githubusercontent.com/72948731/140199129-0b13fb52-7866-4a1f-b144-69d5670e7cb5.png)

Good job on recursive functions, and it was clear that you did the collegeboard video part as well as the PBL part.

One thing to improve is maybe have something to show about databased since you worked on them too but if you present that in class that is good as well.
